services:
  backend:
    build: backend/
    image: profiler/backend
    container_name: ai-profiler-backend
    volumes:
      - ./datasets:/app/datasets

  frontend:
    build: frontend/
    image: profiler/frontend
    container_name: ai-profiler-frontend
    ports:
      - 3000:3000
