services:
  db:
    image: mongo
    container_name: ai-profiler-database
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 30s

  backend:
    build: backend/
    image: profiler/backend
    container_name: ai-profiler-backend
    volumes:
      - ./datasets:/app/datasets

  frontend:
    build: frontend/
    image: profiler/frontend
    container_name: ai-profiler-frontend
    ports:
      - 3000:3000
