pipeline:
  label: english
  estimator: Pipeline
  estimator_pkg: sklearn.pipeline
  estimator_params:
    steps:
      - clean html
      - detwittify
      - count 3grams tfidf
      - svr

svr:
  label: svr
  estimator: SVR
  estimator_pkg: sklearn.svm

tfidf:
  label: count 3grams tfidf
  estimator: TfidfVectorizer
  estimator_pkg: sklearn.feature_extraction.text
  estimator_params:
    analyzer: char
    ngram_range: [3, 3]

html cleaner:
  label: clean html
  estimator: clean_html
  estimator_pkg: pan.preprocess

detwittifier:
  label: detwittify
  estimator: detwittify
  estimator_pkg: pan.preprocess

printer:
  label: printer
  estimator: PrintWrapper
  estimator_pkg: tictacs.wrappers
