#expose classes to predict for this language
# for each class expose the column in the truth.txt file
# and whether it is a classification or regression problem

userid:
    column: 0
    data_only: True
    result_column: 0
    result_label: id
media:
    data_only: True
    result_column: 1
    result_label: type
lang:
    data_only: True
    result_column: 2
    result_label: lang
gender:
    column: 1
    type: classification
    recipe: gender.yml
    result_column: 3
    result_label: gender
extroverted:
    column: 3
    type: regression
    recipe: extroverted.yml
    result_column: 4
    result_label: extroverted
stable:
    column: 4
    type: regression
    # recipe: stable.yml
    recipe: extroverted.yml
    result_column: 5
    result_label: stable
agreeable:
    column: 5
    type: regression
    # recipe: agreeable.yml
    recipe: extroverted.yml
    result_column: 6
    result_label: agreeable
concientious:
    column: 6
    type: regression
    # recipe: concientious.yml
    recipe: extroverted.yml
    result_column: 7
    result_label: concientious
open:
    column: 7
    type: regression
    # recipe: open.yml
    recipe: extroverted.yml
    result_column: 8
    result_label: open
