import Head from "next/head";
import styles from "@/styles/Home.module.css";
import PieChart from "@/components/pieChart/pieChart";
import Chart from "chart.js/auto";
import { CategoryScale } from "chart.js";

Chart.register(CategoryScale);

export default function Home() {
  const data = {
    labels: ["Male", "Female"],
    datasets: [
      {
        label: "Number of people",
        data: [55, 96],
        backgroundColor: ["#98EECC", "#79E0EE"],
        borderWidth: 2,
        borderColor: "rgb(30, 32, 44)",
      },
    ],
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>RESULTS OVERVIEW</h1>

        <div className={styles.chartsContainer}>
          <PieChart chartData={data} />
          <PieChart chartData={data} />
          <PieChart chartData={data} />
        </div>
      </main>
    </>
  );
}
